# Generated by Django 2.0.3 on 2020-03-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('body', models.TextField(max_length=300)),
            ],
        ),
    ]
